# -------------------------------------
# Basic Site Configuration
# -------------------------------------

# Basic Site Settings
locale                   : "en-IN"
title                    : "arnav"
title_separator          : "-"
name                     : &name "arnav"
description              : &description "Research Intern @ NIH (US) @ Harvard / @ IIT BBS | ML @ JuliaHealth | Prev. Research Intern @ UCLA | Building @ DreamSkrin"
url                      : https://w2sg-arnav.github.io
baseurl                  : "" # e.g., "/blog" for subpath
repository               : "w2sg-arnav/w2sg-arnav.github.io"

# -------------------------------------
# Author Information
# -------------------------------------

author:
  # Biographic Information
  avatar           : "KB.jpg"
  name             : "aka smokiee"
  pronouns         : # e.g., "she/her"
  bio              : "Research Intern @ NIH (US) @ Harvard / @ IIT BBS | ML @ JuliaHealth | Prev. Research Intern @ UCLA | Building @ DreamSkrin"
  location         : "Mumbai, MH, IN"
  employer         : "University of Mumbai"
  uri              : # URL
  email            : "sonavane.arnav2@gmail.com"

  # Academic Websites
  arxiv            : # URL
  googlescholar    : "https://scholar.google.com/citations?user=5u4nSbMAAAAJ&hl=en&oi=ao"
  orcid            : "https://orcid.org/0009-0006-0601-056X"
  
  # Repositories and Software Development
  github           : "w2sg-arnav"
  kaggle           : arnavsonavane

  # Social Media
  instagram        : "arnav_mcmxvi"
  linkedin         : "arnavsonavane"
  twitter          : "arnxv_eh"

# -------------------------------------
# Publications Configuration
# -------------------------------------

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# -------------------------------------
# Site Settings
# -------------------------------------

teaser                   : # filename in /images/, e.g., "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# Comments Configuration
comments:
  provider               : # "disqus", "discourse", "facebook", "google-plus", etc.
  disqus:
    shortname            : 
  discourse:
    server               : # e.g., meta.discourse.org

# -------------------------------------
# Social Sharing and SEO
# -------------------------------------

twitter:
  username               : &twitter "arnxv_eh"
og_image                 : # default site image for Open Graph/Twitter

linkedin:
  type                   : # "Person" or "Organization"
  name                   : # Custom name if different from site name
  links: # Social profile links array

# SEO Verification
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# -------------------------------------
# Analytics
# -------------------------------------

analytics:
  provider               : "false" # options: false, "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :

# -------------------------------------
# File Management
# -------------------------------------

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# -------------------------------------
# Markdown Processing and Conversion
# -------------------------------------

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# -------------------------------------
# Collections Settings
# -------------------------------------

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Page Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# -------------------------------------
# Sass/SCSS Configuration
# -------------------------------------

sass:
  sass_dir: _sass
  style: compressed

# -------------------------------------
# Output Settings
# -------------------------------------

permalink: /:categories/:title/
timezone: Etc/UTC # Check: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# -------------------------------------
# Plugin Configuration
# -------------------------------------

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
